apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: r46bf2opf-nodejs 
  janus-idp.io/tekton: r46bf2opf-nodejs
  backstage.io/kubernetes-id: r46bf2opf-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r46bf2opf-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  