apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: r46bf2opf-nodejs
  janus-idp.io/tekton: r46bf2opf-nodejs
  backstage.io/kubernetes-id: r46bf2opf-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r46bf2opf-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
